### ISSUE TITLE
FailedAttachVolume / timeout expired waiting for volumes to attach or mount for pod

### ISSUE THREAD

**Issue by kjellberg** [digitalocean/csi-digitalocean#122]
### What did you do?

First I created a PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-shared-csi-pvc
  namespace: mysql-shared
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

Then a deployment:
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-shared
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-shared-csi-pvc
```

And what I get is:
![screenshot 2019-01-13 12 44 46](https://user-images.githubusercontent.com/2277443/51084860-200bee80-1731-11e9-94d8-68b31eda5c61.png)

The volume was created, can be found in DO and is attached to the correct node/droplet:

![screenshot 2019-01-13 12 49 32](https://user-images.githubusercontent.com/2277443/51084881-bc35f580-1731-11e9-91e0-763d69a76b42.png)

* kubectl describe pods -n mysql-shared
```
Name:               mysql-57bc66b64b-rzld9
Namespace:          mysql-shared
Priority:           0
PriorityClassName:  <none>
Node:               stoic-lichterman-8uai/10.135.80.232
Start Time:         Sun, 13 Jan 2019 12:11:04 +0100
Labels:             app=mysql
                    pod-template-hash=57bc66b64b
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/mysql-57bc66b64b
Containers:
  mysql:
    Container ID:   
    Image:          mysql:5.7
    Image ID:       
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      MYSQL_ROOT_PASSWORD:  9fbbq09n8j8uasfa79fb
    Mounts:
      /var/lib/mysql from mysql-persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pwc47 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mysql-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-shared-csi-pvc
    ReadOnly:   false
  default-token-pwc47:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pwc47
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                From                            Message
  ----     ------                  ----               ----                            -------
  Normal   Scheduled               29m                default-scheduler               Successfully assigned mysql-shared/mysql-57bc66b64b-rzld9 to stoic-lichterman-8uai
  Warning  FailedAttachVolume      29m (x4 over 29m)  attachdetach-controller         AttachVolume.Attach failed for volume "pvc-e47f3e42-1722-11e9-a7a2-0693a3a6295d" : rpc error: code = Unknown desc = Get https://api.digitalocean.com/v2/volumes/e51f5fb2-1722-11e9-aba1-0a58ac14d104: read tcp 157.230.104.133:50630->104.16.25.4:443: read: connection reset by peer
  Normal   SuccessfulAttachVolume  28m                attachdetach-controller         AttachVolume.Attach succeeded for volume "pvc-e47f3e42-1722-11e9-a7a2-0693a3a6295d"
  Warning  FailedMount             6m (x10 over 27m)  kubelet, stoic-lichterman-8uai  Unable to mount volumes for pod "mysql-57bc66b64b-rzld9_mysql-shared(eb0ef4bc-1723-11e9-a7a2-0693a3a6295d)": timeout expired waiting for volumes to attach or mount for pod "mysql-shared"/"mysql-57bc66b64b-rzld9". list of unmounted volumes=[mysql-persistent-storage]. list of unattached volumes=[mysql-persistent-storage default-token-pwc47]
  Warning  FailedMount             2m (x21 over 28m)  kubelet, stoic-lichterman-8uai  MountVolume.MountDevice failed for volume "pvc-e47f3e42-1722-11e9-a7a2-0693a3a6295d" : rpc error: code = Internal desc = formatting disk failed: exit status 1 cmd: 'mkfs.ext4 -F /dev/disk/by-id/scsi-0DO_Volume_pvc-e47f3e42-1722-11e9-a7a2-0693a3a6295d' output: "mke2fs 1.43.7 (16-Oct-2017)\nThe file /dev/disk/by-id/scsi-0DO_Volume_pvc-e47f3e42-1722-11e9-a7a2-0693a3a6295d does not exist and no size was specified.\n"
```

### What did you expect to happen?

I expect a pod to be created and a volume to be formatted without any errors.

* CSI Version:
quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
digitalocean/do-csi-plugin:v1.0.0

* Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

I've created a lot of volumes before, but it suddenly stopped working. Maybe I've deleted something important by mistake when I was playing around with old PVC configs? 

`cluster-info dump` gives me around 600.000 rows, with some info I don't want to share here, so I'm not sure it's a good idea to just paste it. But will do if needed. 

Thanks
