### ISSUE TITLE
Reclaim policy switching to Retain instead of Delete

### ISSUE THREAD

**Issue by tobiasvdp** [digitalocean/csi-digitalocean#126]
Is it safe to recreate the storage class with reclaim policy: Retain? For data safety when we need to resize for example it's dangerous to delete the volume when the claim gets removed.

### What did you do? (required. The issue will be **closed** when not provided.)
Deleted claim resulting in the block storage being deleted

### What did you expect to happen?
the option for reclaimoption Retain

### Configuration (**MUST** fill this out):
Bare bones Kube 1.13 with csi applied to.

**Comment by Berndinox** [comment]
+1
Cloning the Default DO Storageclass and updatig the Reclaim-Policy didnt work for me..

**Comment by kallisti5** [comment]
I just ran into this issue. Could this be documented?  The normal way involves applying this to the PersistentVolume vs the PersistentVolumeClaim

**Comment by kallisti5** [comment]
*actually*, I changed the storageClassName to do-block-storage-persist.  While it applies to my k8s cluster, the volume doesn't actually get created.

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: do-block-storage-persist
```

**Comment by kallisti5** [comment]
```
$ kubectl apply -f git.yml
deployment.apps "git-deployment" created
persistentvolumeclaim "gerrit-data-pvc" created
service "cgit" created
service "review" created
ingress.extensions "git" created

$ kubectl get pvc
NAME              STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS               AGE
gerrit-data-pvc   Pending                                       do-block-storage-persist   5m


$ kubectl get pv
No resources found.
```

Actually, just looks like ```do-block-storage-persist``` is broken and never allocates. It doesn't show up in the DO volume dashboard.

**Comment by Berndinox** [comment]
Hy,

i set the wron name:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
{"storageclass.kubernetes.io/is-default-class":"false"},"name":"**do-block-storage-persist**"},"provisioner":"dobs.csi.digitalocean.com"}
    storageclass.kubernetes.io/is-default-class: "false"
  name: do-block-storage-persist
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
