### ISSUE TITLE
add support for xfs format

### ISSUE THREAD

**Issue by hbinduni** [digitalocean/csi-digitalocean#135]
Hi, i try to format my persistent volume to xfs but it seem failed:

```
Events:
  Type     Reason                  Age               From                      Message
  ----     ------                  ----              ----                      -------
  Normal   Scheduled               18s               default-scheduler         Successfully assigned default/my-csi-app to hbinduni-1-7tcl
  Normal   SuccessfulAttachVolume  12s               attachdetach-controller   AttachVolume.Attach succeeded for volume "pvc-f7fe24a8-5410-11e9-a36d-2af020f9be33"
  Warning  FailedMount             2s (x5 over 10s)  kubelet, hbinduni-1-7tcl  MountVolume.MountDevice failed for volume "pvc-f7fe24a8-5410-11e9-a36d-2af020f9be33" : rpc error: code = Internal desc = exec: "mkfs.xfs": executable file not found in $PATH
```

i know in the digitalocean/volume tab product, you can create and format xfs, but i dont know why it is failed.

this is my system detail:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pod-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage-xfs
```

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage-xfs
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"false"},"name":"do-block-storage-xfs"},"provisioner":"dobs.csi.digitalocean.com"}
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: dobs.csi.digitalocean.com
parameters:
  fstype: xfs
```

**Comment by bjg2** [comment]
I am also interested in how to create XFS persistent volume. XFS is better than ext4 for some usecases, like databases.

**Comment by aleshaczech** [comment]
Hi, facing the same issue:
```
Warning  FailedMount             1s (x3 over 3s)  kubelet, pool-wlvtlt8ip-foo4  MountVolume.MountDevice failed for volume "pvc-546ee38c-7320-11e9-ac84-36ad47952348" : rpc error: code = Internal desc = exec: "mkfs.xfs": executable file not found in $PATH
```
Kubernetes config:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-retain-xfs
provisioner: dobs.csi.digitalocean.com
parameters:
  fsType: xfs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-retain-xfs
```
