### ISSUE TITLE
DO provisioned volume is not formatted to its maximum free space

### ISSUE THREAD

**Issue by chatsatourian** [digitalocean/csi-digitalocean#175]
### What did you do?

- Created 3 volumes with doctl.
- Created 3 persistent volumes with volume handles referring to the previously created volumes.
- Created 3 persistent volume claims for the 3 persistent volumes.
- Created a dummy headless service for the stateful set.
- Created a stateful set with 3 replicas and a volume claim template.

### What did you expect to happen?

I expected a stateful set with 3 replicas and a volume with the requested size attached on each. Unfortunately, the size available was approximately 380M.

I managed to resize one of the affected volumes with resize2fs while the volume was detached. In order to detach the volume I killed the pod that was using it. When the pod was recreated, the available size was the expected. Since multiple volumes were affected by this issue every time I reproduced it, I continued the troubleshooting to find something more suitable.

The do-csi-plugin checks if the volume is formatted with the mounter.IsFormatted function. The problem is that this function uses blkid to simply check if there is a record for the volume in question. It does not seem to check the file system or the size requested by the user. In my case the volume is formatted to EXT4 but for some reason the size is not maxed out. Since there is a record for the volume, the function returns true and the do-csi-plugin skips formatting the volume.

I pushed an image where I disabled the mounter.IsFormatted function and forced the formatting of the volume. The next problem I encountered was that one of the nodes was of different type, s-4vcpu-8gb instead of s-2vcpu-4gb like the rest, and the volume was not detached so that the do-csi-plugin could format it.

### Configuration:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-hs
  namespace: test
  labels:
    application: busybox
spec:
  clusterIP: None
  selector:
    application: busybox
  ports:
    - port: 80
```
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-busybox-0
  namespace: test
spec:
  storageClassName: do-block-storage
  volumeName: test-busybox-0-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: busybox
      do-availability-zone: fra1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-busybox-1
  namespace: test
spec:
  storageClassName: do-block-storage
  volumeName: test-busybox-1-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: busybox
      do-availability-zone: fra1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-busybox-2
  namespace: test
spec:
  storageClassName: do-block-storage
  volumeName: test-busybox-2-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: busybox
      do-availability-zone: fra1
```
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-busybox-0-pv
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  labels:
    name: busybox
    do-availability-zone: fra1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-busybox-0
    namespace: test
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 6801f6fd-aa0a-11e9-9bfb-0a58ac14d11d
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-busybox-1-pv
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  labels:
    name: busybox
    do-availability-zone: fra1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-busybox-1
    namespace: test
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 6b6aef28-aa0a-11e9-babe-0a58ac14d0b7
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-busybox-2-pv
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  labels:
    name: busybox
    do-availability-zone: fra1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-busybox-2
    namespace: test
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 6f7b9d03-aa0a-11e9-9bfb-0a58ac14d11d
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"
```
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: test
  labels:
    application: busybox
spec:
  podManagementPolicy: Parallel
  replicas: 3
  serviceName: busybox-hs
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: busybox
  template:
    metadata:
      labels:
        application: busybox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - test
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: application
                    operator: In
                    values:
                      - busybox
      containers:
        - name: ubuntu
          image: ubuntu:19.04
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/lib/busybox
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 75m
              memory: 128Mi
          command: ["/bin/sh", "-c"]
          args: ["sleep 36000"]
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: test
        labels:
          application: busybox
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

```

* CSI Version: v1.1.0 updated to v1.1.1

* Kubernetes Version: v1.14.1

* Cloud provider: DigitalOcean
