### ISSUE TITLE
Openshift Origin v3.11 - Volume doesn't get reattached after pod stops working

### ISSUE THREAD

**Issue by ajvn** [digitalocean/csi-digitalocean#224]
### What did you do? (required. The issue will be **closed** when not provided.)
What works:
- Deploying the driver works, everything starts fine.
- Creating PVC works fine by using example in Github page.
- Creating example POD also works fine, volume attaches properly.

What doesn't work:
- After pod is deleted for whatever reason, instead of volume getting unmounted and reattached to recreated pod, error occurs:

```level=error msg="method failed" error="mount propagation for target \"/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount\" is not enabled" method=/csi.v0.Node/NodeUnstageVolume node_id=XXXXXXXXX region=obfuscated1 version=v0.2.0```

This prevents pod from recreating. If we try to create new pod to use that pvc, that error will keep showing. 

However, if we restart/recreate pod that's responsible for mounting/unmounting those volumes (csi-do-node-xxxxx), everything starts working again.
This is the log:
```
time="2019-12-05T16:49:30Z" level=info msg="removing socket" node_id=XXXXXXX region=obfuscated1 socket=/csi/csi.sock version=v0.2.0
time="2019-12-05T16:49:31Z" level=info msg="server started" addr=/csi/csi.sock node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:31Z" level=info msg="get plugin info called" method=get_plugin_info node_id=XXXXXX region=obfuscated1 response="name:\"com.digitalocean.csi.dobs\" vendor_version:\"v0.2.0\" " version=v0.2.0
time="2019-12-05T16:49:31Z" level=info msg="node get id called" method=node_get_id node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:57Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc: " node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:57Z" level=info msg="node unstage volume called" method=node_unstage_volume node_id=XXXXXX region=obfuscated1 staging_target_path=/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount version=v0.2.0 volume_id=aec66fdf-xxxx-xxxx-xxxx-xxxxxx14d019
time="2019-12-05T16:49:57Z" level=info msg="checking if target is mounted" args="[-o TARGET,PROPAGATION,FSTYPE,OPTIONS -M /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount -J]" cmd=findmnt node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:57Z" level=info msg="staging target path is already unmounted" method=node_unstage_volume node_id=XXXXXX region=obfuscated1 staging_target_path=/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount version=v0.2.0 volume_id=aec66fdf-xxxx-xxxx-xxxx-xxxxxx14d019
time="2019-12-05T16:49:57Z" level=info msg="unmounting stage volume is finished" method=node_unstage_volume node_id=XXXXXX region=obfuscated1 staging_target_path=/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount version=v0.2.0 volume_id=aec66fdf-xxxx-xxxx-xxxx-xxxxxx14d019
```

For some reason it fails this [check on line 260](https://github.com/digitalocean/csi-digitalocean/blob/e749e467fddbfdbe1e2d874625922159d12a40e5/driver/mounter.go#L260-L274) while actual csi-do-node-xxxx is running after example pod gets deleted, and then this [function is not called](https://github.com/digitalocean/csi-digitalocean/blob/e749e467fddbfdbe1e2d874625922159d12a40e5/driver/node.go#L126-L159) .

Recreate csi-do-node-xxxxx and everything starts working properly.

### What did you expect to happen?
Volume should automatically reattach to a pod without need to manually restart csi-do-node-xxxxx pod.

### Configuration (**MUST** fill this out):
Here are some basic information about versions that we're using:
Openshift Origin v3.11(Kubernetes 1.11)
do-csi-plugin:v0.2.0
driver-registrar:v0.3.0
csi-provisioner:v0.3.0
csi-attacher:v0.3.0

Specific namespace is created for this purpose called do-csi-storage.
Specific service account is created for this purpose called digitalocean-csi-role.
That service account is added to privileged security context constraints.
Docker mount propagation is enabled via MountFlags=shared added in systemd service file. 
Secret is created separately.

Log error when this issue happens:
```
level=error msg="method failed" error="mount propagation for target \"/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount\" is not enabled" method=/csi.v0.Node/NodeUnstageVolume node_id=XXXXXXXXX region=obfuscated1 version=v0.2.0
```
Log when csi-do-node-xxxx is restarted and everything starts working again:
```
time="2019-12-05T16:49:30Z" level=info msg="removing socket" node_id=XXXXXXX region=obfuscated1 socket=/csi/csi.sock version=v0.2.0
time="2019-12-05T16:49:31Z" level=info msg="server started" addr=/csi/csi.sock node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:31Z" level=info msg="get plugin info called" method=get_plugin_info node_id=XXXXXX region=obfuscated1 response="name:\"com.digitalocean.csi.dobs\" vendor_version:\"v0.2.0\" " version=v0.2.0
time="2019-12-05T16:49:31Z" level=info msg="node get id called" method=node_get_id node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:57Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc: " node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:57Z" level=info msg="node unstage volume called" method=node_unstage_volume node_id=XXXXXX region=obfuscated1 staging_target_path=/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount version=v0.2.0 volume_id=aec66fdf-xxxx-xxxx-xxxx-xxxxxx14d019
time="2019-12-05T16:49:57Z" level=info msg="checking if target is mounted" args="[-o TARGET,PROPAGATION,FSTYPE,OPTIONS -M /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount -J]" cmd=findmnt node_id=XXXXXX region=obfuscated1 version=v0.2.0
time="2019-12-05T16:49:57Z" level=info msg="staging target path is already unmounted" method=node_unstage_volume node_id=XXXXXX region=obfuscated1 staging_target_path=/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount version=v0.2.0 volume_id=aec66fdf-xxxx-xxxx-xxxx-xxxxxx14d019
time="2019-12-05T16:49:57Z" level=info msg="unmounting stage volume is finished" method=node_unstage_volume node_id=XXXXXX region=obfuscated1 staging_target_path=/var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/csi/pv/pvc-addfaxxxxxxxxea/globalmount version=v0.2.0 volume_id=aec66fdf-xxxx-xxxx-xxxx-xxxxxx14d019
```

Manifest that's in use:
```
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage
  namespace: do-csi-storage
provisioner: com.digitalocean.csi.dobs

---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-do-controller
  namespace: do-csi-storage
spec:
  serviceName: "csi-do"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-do-controller
        role: csi-do
    spec:
      serviceAccount: digitalocean-csi-role
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.3.0
          args:
            - "--provisioner=com.digitalocean.csi.dobs"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-do-plugin
          image: digitalocean/do-csi-plugin:v0.2.0
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
            - "--url=$(DIGITALOCEAN_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: DIGITALOCEAN_API_URL
              value: https://api.digitalocean.com/
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digitalocean-volume
                  key: access-token
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitalocean-csi-role
  namespace: do-csi-storage

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-controller-provisioner-binding
  namespace: do-csi-storage
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi-role
    namespace: do-csi-storage
roleRef:
  kind: ClusterRole
  name: system:csi-external-provisioner
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-controller-attacher-binding
  namespace: do-csi-storage
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi-role
    namespace: do-csi-storage
roleRef:
  kind: ClusterRole
  name: system:csi-external-attacher
  apiGroup: rbac.authorization.k8s.io

---

kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-do-node
  namespace: do-csi-storage
spec:
  selector:
    matchLabels:
      app: csi-do-node
  template:
    metadata:
      labels:
        app: csi-do-node
        role: csi-do
    spec:
      serviceAccount: digitalocean-csi-role
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.3.0
          securityContext:
            privileged: true
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
        - name: csi-do-plugin
          image: digitalocean/do-csi-plugin:v0.2.0
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
            - "--url=$(DIGITALOCEAN_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DIGITALOCEAN_API_URL
              value: https://api.digitalocean.com/
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digitalocean-volume
                  key: access-token
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/origin/openshift.local.volumes/pods/
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
      volumes:
        # TODO(arslan): the registar is not implemented yet
        #- name: registrar-socket-dir
        #  hostPath:
        #    path: /var/lib/kubelet/device-plugins/
        #    type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.digitalocean.csi.dobs
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/pods/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitalocean-csi-role
  namespace: do-csi-storage

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-driver-registrar-binding
  namespace: do-csi-storage
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi-role
    namespace: do-csi-storage
roleRef:
  kind: ClusterRole
  name: csi-do-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io


---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-driver-registrar-role
  namespace: do-csi-storage
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

```
PVC Manifest:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
```
Test pod Manifest:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  #Node selector is used for easier tracking of logs, but same issue arise without it as well.
  nodeSelector:
    kubernetes.io/hostname: node-x.example.com
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: csi-pvc
```

* CSI Version:
0.2.0
* Kubernetes Version:
1.11
* Cloud provider/framework version, if applicable (such as Rancher):
Openshift Origin

**Comment by ajvn** [comment]
Figured it out, problem was with driver mounting `/globalmount` directory in a directory path that wasn't specified in installation manifest, in this part to be precise:
```
     volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/origin/openshift.local.volumes/pods/
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
      volumes:
        # TODO(arslan): the registar is not implemented yet
        #- name: registrar-socket-dir
        #  hostPath:
        #    path: /var/lib/kubelet/device-plugins/
        #    type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.digitalocean.csi.dobs
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/pods/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
```

So, when driver creates directory called `/var/lib/origin/openshift.local.volumes/plugins/`, by default that directory is created with `mountPropagation: "None"`, and propagation defaults to private. 
After specifying `mountPropagation: Bidirectional` for that directory in volume/volumesMount, this [check](https://github.com/digitalocean/csi-digitalocean/blob/e749e467fddbfdbe1e2d874625922159d12a40e5/driver/mounter.go#L260-L274) didn't fail, and everything works properly.

This is how working part looks like right now:
```
volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: volume-mount-dir
              mountPath: /var/lib/origin/openshift.local.volumes/plugins/
              mountPropagation: "Bidirectional"
            - name: pods-mount-dir
              mountPath: /var/lib/origin/openshift.local.volumes/pods/
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
      volumes:
        # TODO(arslan): the registar is not implemented yet
        #- name: registrar-socket-dir
        #  hostPath:
        #    path: /var/lib/kubelet/device-plugins/
        #    type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.digitalocean.csi.dobs
            type: DirectoryOrCreate
        - name: volume-mount-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/plugins/
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/pods/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
```

If you want I can create a pull request for potential Openshift related branch of this driver with working manifest.
If there's no interest in that, I'll close the ticket and hopefully someone else may find this helpful.

**Comment by timoreimann** [comment]
@ajvn glad you figured it out. I definitely wouldn't mind a pull request to help other OpenShift users.

If it's just a couple of extra YAML lines, then we could add those commented out to the relevant release branch. What do you think about that idea?

**Comment by ajvn** [comment]
Hi @timoreimann ,

Yeah, that works as well. Keep in mind however that beside mentioned issues, one more thing doesn't work with provided example in the `release-0.2.0` branch.

```
- name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
              # TODO(arslan): the registrar is not implemented yet
              # - name: registrar-socket-dir
              #   mountPath: /var/lib/csi/sockets/
```

This pod also needs to run privileged, which needs to be specified like this:
```
- name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.3.0
          securityContext:
            privileged: true
```

Also, file that you're providing in 2nd step of `Installing to Kubernetes` with this command doesn't exist:
```command 
kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v0.2.1.yaml
``` 

Actual 0.2.0 version is however accessible via this [link](https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v0.2.0.yaml).

At the moment this manifest works with Openshift Origin 3.11, tested with both `do-csi-plugin:v0.2.1` and `do-csi-plugin:v0.2.0` images.

We'll continue testing it next week, and if we notice any issues, I'll post it in this ticket (hopefully along with solutions):
```
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage
  namespace: do-csi-storage
provisioner: com.digitalocean.csi.dobs

---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-do-controller
  namespace: do-csi-storage
spec:
  serviceName: "csi-do"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-do-controller
        role: csi-do
    spec:
      serviceAccount: digitalocean-csi-role
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.3.0
          args:
            - "--provisioner=com.digitalocean.csi.dobs"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-do-plugin
          image: digitalocean/do-csi-plugin:v0.2.1
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
            - "--url=$(DIGITALOCEAN_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: DIGITALOCEAN_API_URL
              value: https://api.digitalocean.com/
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digitalocean-volume
                  key: access-token
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitalocean-csi-role
  namespace: do-csi-storage

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-controller-provisioner-binding
  namespace: do-csi-storage
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi-role
    namespace: do-csi-storage
roleRef:
  kind: ClusterRole
  name: system:csi-external-provisioner
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-controller-attacher-binding
  namespace: do-csi-storage
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi-role
    namespace: do-csi-storage
roleRef:
  kind: ClusterRole
  name: system:csi-external-attacher
  apiGroup: rbac.authorization.k8s.io

---

kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-do-node
  namespace: do-csi-storage
spec:
  selector:
    matchLabels:
      app: csi-do-node
  template:
    metadata:
      labels:
        app: csi-do-node
        role: csi-do
    spec:
      serviceAccount: digitalocean-csi-role
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.3.0
          securityContext:
            privileged: true
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
        - name: csi-do-plugin
          image: digitalocean/do-csi-plugin:v0.2.1
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
            - "--url=$(DIGITALOCEAN_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DIGITALOCEAN_API_URL
              value: https://api.digitalocean.com/
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digitalocean-volume
                  key: access-token
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: volume-mount-dir
              mountPath: /var/lib/origin/openshift.local.volumes/plugins/
              mountPropagation: "Bidirectional"
            - name: pods-mount-dir
              mountPath: /var/lib/origin/openshift.local.volumes/pods/
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
      volumes:
        # TODO(arslan): the registar is not implemented yet
        #- name: registrar-socket-dir
        #  hostPath:
        #    path: /var/lib/kubelet/device-plugins/
        #    type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.digitalocean.csi.dobs
            type: DirectoryOrCreate
        - name: volume-mount-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/plugins/
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/pods/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitalocean-csi-role
  namespace: do-csi-storage

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-driver-registrar-binding
  namespace: do-csi-storage
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi-role
    namespace: do-csi-storage
roleRef:
  kind: ClusterRole
  name: csi-do-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io


---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-driver-registrar-role
  namespace: do-csi-storage
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
```
