### ISSUE TITLE
How to use with PersistentVolume or StorageClass?

### ISSUE THREAD

**Issue by bukowa** [digitalocean/csi-digitalocean#282]
### What did you do? 
How can i use `PersistentVolume` / `StorageClass` with `PersistentVolumeClaim` in this driver?
````yaml
apiVersion: v1
kind: PersistentVolume
---
apiVersion: v1
kind: PersistentVolumeClaim
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
````
