### ISSUE TITLE
Creating a persistent volume from snapshot and claiming it in a different namespace does not work

### ISSUE THREAD

**Issue by walec51** [digitalocean/csi-digitalocean#290]
### What did you do? (required. The issue will be **closed** when not provided.)

I wanted to create a volume from a snapshot and claimed it in another namespace.

### What did you expect to happen?

Files from the original volume in the pod from another namespace that claimed the new volume. 

### Configuration:

* manifests, such as pvc, deployments, etc.. you used to reproduce:

assuming we already have a persistent volume claim called `data-postgres-reservation-db-0` I apply the following:

```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: postgres-reservation-db-snapshot
  namespace: staging
spec:
  source:
    name: data-postgres-reservation-db-0
    kind: PersistentVolumeClaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-reservation-db-cloned
  namespace: staging
spec:
  dataSource:
    name: postgres-reservation-db-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

I see that the created persistent volume is named `pvc-758f223c-5f28-4ea6-87cb-84994ead9f3b`

I then execute the following commands:

```
kubectl patch pv pvc-758f223c-5f28-4ea6-87cb-84994ead9f3b -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'

kubectl delete pvc postgres-reservation-db-cloned -n staging
kubectl patch pv  pvc-758f223c-5f28-4ea6-87cb-84994ead9f3b -p '{"spec":{"claimRef": null}}'

kubectl delete statefulset postgres-reservation-db -n develop
kubectl delete pvc data-postgres-reservation-db-0 -n develop
```

I then apply:

```
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "data-postgres-reservation-db-0"
  namespace: develop
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
  volumeName: "pvc-758f223c-5f28-4ea6-87cb-84994ead9f3b"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-reservation-db
  namespace: develop
spec:
  serviceName: postgres-reservation-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-reservation-db
  template:
    metadata:
      labels:
        app: postgres-reservation-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          command:
          - "docker-entrypoint.sh"
          - '-c'
          - 'max_connections=20'
          - '-c'
          - 'shared_buffers=64MB'
          env:
          # custom PGDATA because of https://github.com/docker-library/postgres/issues/696#issuecomment-597775260
          - name: PGDATA
            value: /work/data
          - name: POSTGRES_PASSWORD
            value: somePass
          ports:
          - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
          - name: data
            mountPath: /work
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
```

and unfortunately the database in the namespace `develop` starts with an empty `/work` - no files from the original persistent volume are there

*  Kubernetes Version: 1.16.2-do.3
*  Cloud provider/framework version, if applicable (such as Rancher): DigitalOcean
