### ISSUE TITLE
Timeout while listing DO volume snapshots

### ISSUE THREAD

**Issue by PrasadG193** [digitalocean/csi-digitalocean#295]
### What did you do? (required. The issue will be **closed** when not provided.)
I tried creating `VolumeSnapshot` by referencing existing `VolumeSnapshotContent` with manifest like this:
```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot
spec:
  snapshotClassName: do-block-storage
  snapshotContentName: snapcontent-clone
```

### What did you expect to happen?
I was expecting `VolumeSnapshot` resource to be created without any error and status `readyToUse: true` to be set

but instead the resource created failed with the following error in the created `VolumeSnapshot` status
```
status:
  creationTime: null
  error:
  error:
    message: 'Failed to check and update snapshot: failed to list snapshot content
      snapcontent-c4b22fc4-eadc-4d84-bde8-1bccfb3073d4-clone: "rpc error: code = Aborted
      desc = ListSnapshots listing volume snapshots has failed: Get https://api.digitalocean.com/v2/snapshots?page=13&per_page=20&resource_type=volume:
      context deadline exceeded"'
    time: "2020-04-04T16:38:53Z"
  readyToUse: false
  restoreSize: null

```
I am assuming this due to timeout reached while quering the snapshot resource since we have large number of snapshot created i.e around 270+. When we cleaned up the existing snapshot, the resource got created.

### Configuration (**MUST** fill this out):
manifests used to reproduce the issue:

volumesnapshotcontent.yaml
```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotContent
metadata:
  name: snapcontent-clone
spec:
  csiVolumeSnapshotSource:
    driver: dobs.csi.digitalocean.com
    restoreSize: 0
    snapshotHandle: xxx-xxx-xx-xx     # Copied from any existing snapshot content 
  deletionPolicy: Delete
  snapshotClassName: do-block-storage
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1alpha1
    kind: VolumeSnapshot
    name: new-snapshot
    namespace: default
```

volumesnapshot.yaml
```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot
spec:
  snapshotClassName: do-block-storage
  snapshotContentName: snapcontent-clone
```

* CSI Version: v1.2.0

* Kubernetes Version: v1.16.6

* Cloud provider/framework version, if applicable (such as Rancher): DigitalOcean managed Kubernetes
