### ISSUE TITLE
Feature Request : Allow created resources to have a name prefix

### ISSUE THREAD

**Issue by peterver** [digitalocean/csi-digitalocean#30]
At the moment when for example a volume is provisioned through CSI it gets assigned a name that is bound to be unique.

Such as pvc-123456789ewqioequwq

This approach works beautifully for a purely machine-based operator. But since there is no way to prefix a resource name it leads to confusion when looking at the digitalocean volumes list, especially when the volumes that are provisioned have different use cases.

As such it would/could be beneficial to allow for a prefix to be set ( a prefix, not an override ).

For example : let's say a pvc creates a 10Gb volume for a mysql backup and one for a mongo backup, the resources created by csi would be something like 

- pvc-ewqio4234eew423qquwq
- pvc-jsaldjwui4233oe4234234

Which would be understandable for an automated system, but is not understandable to a human operator just looking at the digitalocean volume list either through doctl or the web interface.

If a prefix is allowed, it could become something like : 

- staging-mysql-pvc-ewqio4234eew423qquwq
- staging-mongo-pvc-jsaldjwui4233oe4234234

**Comment by fatih** [comment]
Hi Peter,

I've looked into it and I think this is something we can do. As I know the name is not unique and can be changeable easily. However I have to first check out what the best way would to set a prefix (such as via CSI parameters or arguments to the CSI plugin)

**Comment by fatih** [comment]
So @peterver I looked into it, and this is doable via the `StorageClass` parameter:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: com.digitalocean.csi.dobs
parameters:
  volumePrefix: "csi-digitalocean"
```

And then in our `controller.go` we can do a:

```go
volumeName := req.Name
// change the name if the storage-class has a prefix option
prefix, ok := req.Parameters[volumePrefixParam]
if ok {
	volumeName = prefix + "-" + volumeName
}
```

However, I'm not sure how this would be helpful because the there is a single `StorageClass` option and therefore it's global and not bound to the `PVC` you're creating. I don't think there is a way to pass down any information from a `PVC` down to the `CSI` plugin. I'm going to ask this to `#sig-storage` to see if this is something we can work on.
