### ISSUE TITLE
csi-do-controller-0 CrashLoopBackOff

### ISSUE THREAD

**Issue by max3903** [digitalocean/csi-digitalocean#328]
### What did you do? (required. The issue will be **closed** when not provided.)

I followed the documentation to add the do-block-storage plugin:

I added the secret successfully and run:

```
kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v1.3.0.yaml
```

It fails on some snapshot specific stuff:
```
CustomResourceDefinition.apiextensions.k8s.io "volumesnapshots.snapshot.storage.k8s.io" is invalid: spec.version: Invalid value: "v1alpha1": must match the first version in spec.versions
```

I moved on and tried to create a PVC.

### What did you expect to happen?

I was expecting the PV to be created.

### Configuration (**MUST** fill this out):

* system logs:

https://gist.github.com/max3903/acb18527be1138a33d77f3eaaddb89a8

* manifests, such as pvc, deployments, etc.. you used to reproduce:

secret.yaml:

```
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  access-token: "3e8[...]ec5"
```

pvc.yaml:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
```

* CSI Version:

1.3.0

* Kubernetes Version:

1.17

* Cloud provider/framework version, if applicable (such as Rancher):

OKD 4.5
