### ISSUE TITLE
Feature request: allow custom snapshot names

### ISSUE THREAD

**Issue by maxfliri** [digitalocean/csi-digitalocean#427]
When I create a VolumeSnapshot, the corresponding DO snapshot created by the CSI is given a name like `snapshot-8fb09ea8-d2af-465f-9a84-e121351aaf5b`, with the prefix `snapshot-` followed by a UUID. This makes it hard to understand what a snapshot contains, and which is the corresponding kubernetes VolumeSnapshot.

I'd like to be able to somehow specify the name of the underlying snapshot created by the CSI. This would allow me to give meaningful names to the snapshots, so that I can identify these more easily.

For example, one way of doing this could be using annotations on the VolumeSnapshot metadata:

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: db-snapshot-1
  annotations:
    csi.digitalocean.com/do-snapshot-name: db-snapshot-1
spec:
  source:
    persistentVolumeClaimName: wordpress-html
  volumeSnapshotClassName: do-block-storage
```

This would instruct the CSI to use `db-snapshot-1` as the name for the result DigitalOcean snapshot.
