### ISSUE TITLE
Error: waiting for a volume to be created, either by external provisioner "dobs.csi.digitalocean.com" or manually created by system administrator

### ISSUE THREAD

**Issue by icleitoncosta** [digitalocean/csi-digitalocean#428]
### What did you do? (required. The issue will be **closed** when not provided.)
I'm using Cloud outside DigitalOcean, i'm need to use a Volume 
Im install cert-manager 
and install CSI-Diver (without error logs):

`kubectl apply -fhttps://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v4.0.0/{crds.yaml,driver.yaml,snapshot-controller.yaml}`

I'm try to create PVC for test

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
```
When i type `kubectl describe pvc csi-pvc` i'm get this result:
```
:~# kubectl describe pvc csi-pvc
Name:          csi-pvc
Namespace:     ingress-nginx
StorageClass:  do-block-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
               volume.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  ExternalProvisioning  13s (x13 over 3m1s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "dobs.csi.digitalocean.com" or manually created by system administrator
```

### What did you expect to happen?
After that, it was to create the PV, but it is only locked in this step.

### Configuration (**MUST** fill this out):

* system logs:

Please provide the following logs:

```

kubectl cluster-info dump > kubernetes-dump.log
```
[https://gist.github.com/icleitoncosta/2fc3a95c6c96e2e9d36f7f1ddef98bdb]

* manifests, such as pvc, deployments, etc.. you used to reproduce:

secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  access-token: "dop_v1_9b02[...]b79d2"
```

pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

```

* CSI Version:
4.0.0

* Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

```

* Cloud provider/framework version, if applicable (such as Rancher):
Contabo
