### ISSUE TITLE
PVC fails to mount using RancherOS

### ISSUE THREAD

**Issue by roccolangeweg** [digitalocean/csi-digitalocean#43]
Hi,

When trying to create a PVC and attaching it, it fails due to the below error:

MountVolume.MountDevice failed for volume "pvc-2be219db-955f-11e8-9a13-e6af7cff535a" : rpc error: code = Unavailable desc = grpc: the connection is unavailable

Tried with both 1.10 and 1.11

OS: RancherOS 1.4
Kubernetes 1.10

**Comment by fatih** [comment]
Hi @roccolangeweg 

Please use Rancher `2.0.x` with this setting: https://github.com/digitalocean/csi-digitalocean#rancher-users The issue above seems to be a network issue and not a CSI specific problem. Let me know how this works out for you and please reopen if it doesn't solve your issue. Thanks!

**Comment by roccolangeweg** [comment]
Hi @fatih,

I've recreated the cluster adding the described info to the Rancher Cluster Options YAML file. Unfortunately, I'm still running into the same error.

**Comment by roccolangeweg** [comment]
```
addon_job_timeout: 30
authentication: 
  strategy: "x509"
bastion_host: 
  ssh_agent_auth: false
ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.10.5-rancher1-1"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  plugin: "canal"
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube_api: 
    extra_args: 
      feature-gates: "MountPropagation=true"
    pod_security_policy: false
  kubelet: 
    extra_args: 
      feature-gates: "MountPropagation=true"
    fail_swap_on: false
ssh_agent_auth: false
```
