### ISSUE TITLE
Feature Request: Support Online PV Resizing

### ISSUE THREAD

**Issue by varshavaradarajan** [digitalocean/csi-digitalocean#570]
### What did you do? (required. The issue will be **closed** when not provided.)
Try to resize an in-use volume by changing the pvc.spec.request.storage value to higher than previously set: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#csi-volume-expansion

### What did you expect to happen?
I shouldn't have to delete the pod which has the volume mounted. Instead I get FileSystemResizePending: Waiting for user to (re-)start a pod to finish file system resize of volume on node.

### Configuration (**MUST** fill this out):

* manifests, such as pvc, deployments, etc.. you used to reproduce:

```
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: csi-pod-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pod-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

```
Once volume is provisioned, kubectl edit pvc to change spec.resources.requests.storage to 8G. PV gets resized, But PVC capacity remains at 5G with the FileSystemResizePending message. 

* CSI Version: v4.7.0 (also latest)

* Kubernetes Version: 1.26.9 (also on latest version )

* Cloud provider/framework version, if applicable (such as Rancher): 1.26.9-do.0  (also on latest version)
