### ISSUE TITLE
PersistentVolumeClaim stuck at "pending" state

### ISSUE THREAD

**Issue by lucasecdb** [digitalocean/csi-digitalocean#69]
### What did you do?
I've initialized my cluster with `kubeadm init --pod-network-cidr=192.168.0.0/16` and followed the instructions provided in the README, stopping after the creation of the pvc.

### What did you expect to happen?
For the PV to be created.

### Configuration:
My PVC configuration:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: cramkle
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

* CSI Version: v0.1.4

* Kubernetes Version: v1.11.2
