### ISSUE TITLE
Connect existing block storage volumes?

### ISSUE THREAD

**Issue by feluxe** [digitalocean/csi-digitalocean#85]
Hi there,

is it possible to use *csi-digitalocean* to connect a kubernetes pod to an existing block storage volume?

I looked at the docs, examples and the issues, but I couldn't find anything related to this.

**Comment by Richard87** [comment]
Following (I'm also interested in this, specifically in a recovery, how do I reattach volumes to a new cluster if necessary?)

**Comment by feluxe** [comment]
I was using the [stackpoint digitalocean provisioner](StackPointCloud/digitalocean-flex-volume) before and there you could select a volume via `VolumeName` and `VolumeID` in a `PV` and add a `claimRef` to bind a `PVC` to the `PV`. The configs for it looked like [this](https://github.com/StackPointCloud/digitalocean-flex-volume/issues/7#issuecomment-378089475). It worked quite well.

**Comment by fatih** [comment]
This is not currently possible with the CSI plugin because there is no way to pass down metadata (i.e `annotations`). If that would be possible, we could pass down the existing volume name via the PVC, such as: 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  annotations:
    volumeId: "2478ae4c-c31f-44s8-5242-0a58ac14d085"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
```

Then our CSI plugin could read the annotations and decide **not** to create a new volume and instead re-use the existing volume. 

There is an open issue that tracks this feature in the CSI spec and K8S, see: https://github.com/kubernetes-csi/external-provisioner/issues/86 Until there is an official way of doing this, it's not possible unfortunately.
