### ISSUE TITLE
Able to create volume, but unable to mount it to pod

### ISSUE THREAD

**Issue by badri** [digitalocean/csi-digitalocean#93]
### What did you do? (required. The issue will be **closed** when not provided.)

I tried to create a new DO storage class using this plugin for my OpenShift 3.10 cluster.

### What did you expect to happen?

A new volume gets created and mounted to the pod.

### Configuration (**MUST** fill this out):

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: com.digitalocean.csi.dobs


---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digitalocean-csi-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digitalocean-csi-role
subjects:
  - kind: ServiceAccount
    name: digitalocean-csi
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: digitalocean-csi-role
  apiGroup: rbac.authorization.k8s.io

---

kind: Secret
apiVersion: v1
type: Opaque
stringData:
  access-token: "xyz"
metadata:
  name: digitalocean

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: digitalocean-csi-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digitalocean-csi-controllers
  template:
    metadata:
      labels:
        app: digitalocean-csi-controllers
    spec:
      serviceAccount: digitalocean-csi
      containers:
        - name: csi-attacher
          image: lakshminp/csi-attacher:v3.10
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--leader-election-namespace=$(MY_NAMESPACE)"
            - "--leader-election-identity=$(MY_NAME)"
          env:
            - name: MY_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-provisioner
          image: lakshminp/csi-provisioner:v3.10
          args:
            - "--v=5"
            - "--provisioner=com.digitalocean.csi.dobs"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: digitalocean-driver
          image: digitalocean/do-csi-plugin:v0.2.0
          args :
            - "--endpoint=unix://$(ADDRESS)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
            - "--url=$(DIGITALOCEAN_API_URL)"
          env:
            - name: NODEID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName            
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DIGITALOCEAN_API_URL
              value: https://api.digitalocean.com/
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digitalocean
                  key: access-token
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: digitalocean-csi-ds
spec:
  selector:
    matchLabels:
      app: digitalocean-csi-driver
  template:
    metadata:
      labels:
        app: digitalocean-csi-driver
    spec:
      nodeSelector:
          role: node
      serviceAccount: digitalocean-csi
      containers:
        - name: csi-driver-registrar
          image: registry.access.redhat.com/openshift3/csi-driver-registrar:v3.10
          securityContext:
            privileged: true
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: digitalocean-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: digitalocean/do-csi-plugin:v0.2.0
          args :
            - "--endpoint=unix://$(ADDRESS)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
            - "--url=$(DIGITALOCEAN_API_URL)"
          env:
            - name: NODEID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DIGITALOCEAN_API_URL
              value: https://api.digitalocean.com/
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: digitalocean
                  key: access-token
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /var/lib/origin/openshift.local.volumes/pods/
              mountPropagation: "Bidirectional"
            - name: cloud-metadata
              mountPath: /var/lib/cloud/data/
            - name: dev
              mountPath: /dev
      volumes:
        - name: cloud-metadata
          hostPath:
            path: /var/lib/cloud/data/
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.digitalocean.csi.dobs
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/pods/
            type: Directory
        - name: dev
          hostPath:
            path: /dev

```

* system logs:

from pod:

```
I1024 16:04:13.418610       1 csi_handler.go:330] Saved attach error to "csi-c8af0f7c0ba46bafd1a40b16396a1f03edaeeb51acdc7da1666c2a0db8d6e2b6"
I1024 16:04:13.418658       1 csi_handler.go:86] Error processing "csi-c8af0f7c0ba46bafd1a40b16396a1f03edaeeb51acdc7da1666c2a0db8d6e2b6": failed to attach: node "openshift-master" has no NodeID annotation
```

from web console:

```

 
--
12:09:43 PM | postgresql-2-1-9ll8k | Pod | Warning | Failed Mount | Unable to mount volumes for pod "postgresql-2-1-9ll8k_validate(fac2a09e-d7a5-11e8-8c1a-1a5063441dd8)": timeout expired waiting for volumes to attach or mount for pod "validate"/"postgresql-2-1-9ll8k". list of unmounted volumes=[postgresql-2-data]. list of unattached volumes=[postgresql-2-data default-token-fbws6]4 times in the last 21 minutes
12:09:09 PM | postgresql-2-1-9ll8k | Pod | Warning | Failed Attach Volume | AttachVolume.Attach failed for volume "kubernetes-dynamic-pv-f8864c5ed7a511e8" : node "openshift-master" has no NodeID annotation

```

Please provide the following logs:

```

kubectl cluster-info dump > kubernetes-dump.log
```

This will output everthing from your cluster.  Please use a private gist via
https://gist.github.com/ to share this dump with us

* manifests, such as pvc, deployments, etc.. you used to reproduce:

Please provide the **total** set of manifests that are needed to reproduce the
issue. Just providing the `pvc` is not helpful. If you cannot provide it due
privacy concerns, please try creating a reproducible case.

* CSI Version:

v0.2.0

* Kubernetes Version:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-08-03T07:21:49Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-10-12T17:04:15Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Cloud provider/framework version, if applicable (such as Rancher):

DigitalOcean with OpenShift 3.10.

I followed the same instructions as in [OpenShift CSI configuration document](https://docs.openshift.com/container-platform/3.10/install_config/persistent_storage/persistent_storage_csi.html).
